"""
Comprehensive Interactive Dashboard Generator
Creates 24 different visualizations with individual sliders and customization options
"""

import json
from typing import List, Dict
from datetime import datetime


class DashboardGenerator:
    """Generate comprehensive interactive dashboard with 24 visualization types"""
    
    def __init__(self, data: List[Dict], stats: Dict):
        self.data = data
        self.stats = stats
        
    def generate(self, output_file: str) -> str:
        dashboard_file = output_file.replace('.json', '_dashboard.html')
        html_content = self._create_html()
        with open(dashboard_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        return dashboard_file
    
    def _create_html(self) -> str:
        """Create complete HTML dashboard with all 24 visualizations"""
        data_json = json.dumps(self.data, indent=2)
        stats_json = json.dumps(self.stats, indent=2)
        
        # Generate the comprehensive HTML with all 24 visualizations
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python Time Analysis - 24 Visualizations</title>
    
    <!-- Visualization Libraries -->
    <script src="https://unpkg.com/chart.js@4.4.1/dist/chart.umd.js"></script>
    <script src="https://unpkg.com/plotly.js@2.27.0/dist/plotly.min.js"></script>
    <script src="https://unpkg.com/d3@7/dist/d3.min.js"></script>
    
    <style>
{self._get_css()}
    </style>
</head>
<body>
    <div class="dashboard">
        <div class="header">
            <h1>📊 Python Time Analysis - Comprehensive Dashboard</h1>
            <p><strong>24 Interactive Visualizations</strong> • Each with Individual Controls</p>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p class="stats">Data: {len(self.data)} users • {len(self.stats.get('modules', {}))} modules</p>
        </div>
        
        <div class="tabs">
            <button class="tab active" onclick="switchTab(0)">⏰ Time-Based (3)</button>
            <button class="tab" onclick="switchTab(1)">📈 Comparison (3)</button>
            <button class="tab" onclick="switchTab(2)">🎯 Performance (3)</button>
            <button class="tab" onclick="switchTab(3)">🔄 Flow (3)</button>
            <button class="tab" onclick="switchTab(4)">📊 Statistical (3)</button>
            <button class="tab" onclick="switchTab(5)">🏆 Leaderboard (2)</button>
            <button class="tab" onclick="switchTab(6)">🎨 Advanced (4)</button>
            <button class="tab" onclick="switchTab(7)">🎯 Components (3)</button>
        </div>
        
        <div id="content">
            <!-- Content will be generated by JavaScript -->
        </div>
        
        <div class="footer">
            <p>Python Time Analysis Dashboard • All 24 Visualizations with Individual Controls</p>
            <p>Generated by <a href="https://github.com/Pixyde/PythonTime" target="_blank">PythonTime</a></p>
        </div>
    </div>
    
    <script>
        const rawData = {data_json};
        const rawStats = {stats_json};
        
{self._get_javascript()}
    </script>
</body>
</html>"""
        return html

    def _get_css(self) -> str:
        """Generate CSS for the comprehensive dashboard"""
        return """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { 
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
    min-height: 100vh; 
}
.dashboard { max-width: 1600px; margin: 0 auto; padding: 20px; }

/* Header */
.header { 
    background: white; 
    border-radius: 15px; 
    padding: 30px; 
    margin-bottom: 20px; 
    box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
    text-align: center; 
}
.header h1 { color: #667eea; font-size: 2.5rem; margin-bottom: 10px; }
.header p { color: #666; font-size: 1.1rem; margin-top: 8px; }
.header .timestamp { font-size: 0.9rem; color: #999; }
.header .stats { font-weight: bold; color: #764ba2; }

/* Tabs */
.tabs { 
    background: white; 
    border-radius: 15px; 
    padding: 20px; 
    margin-bottom: 20px; 
    box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
    display: flex; 
    gap: 10px; 
    flex-wrap: wrap; 
    justify-content: center;
}
.tab { 
    padding: 12px 24px; 
    border: none; 
    background: #f0f0f0; 
    border-radius: 8px; 
    cursor: pointer; 
    font-size: 0.95rem; 
    transition: all 0.3s; 
    font-weight: 500;
}
.tab:hover { background: #e0e0e0; transform: translateY(-2px); }
.tab.active { background: #667eea; color: white; font-weight: bold; box-shadow: 0 2px 4px rgba(102, 126, 234, 0.3); }

/* Tab Content */
.tab-content { display: none; }
.tab-content.active { display: block; }
.category-title { 
    color: #667eea; 
    font-size: 1.8rem; 
    margin-bottom: 25px; 
    padding: 15px; 
    background: white; 
    border-radius: 10px; 
    text-align: center; 
}

/* Visualization Grid */
.viz-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(550px, 1fr)); gap: 25px; }

/* Visualization Panel */
.viz-panel { 
    background: white; 
    border-radius: 15px; 
    padding: 25px; 
    box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
    transition: all 0.3s;
}
.viz-panel:hover { box-shadow: 0 8px 12px rgba(0,0,0,0.15); transform: translateY(-3px); }

.viz-header { 
    display: flex; 
    justify-content: space-between; 
    align-items: center; 
    margin-bottom: 15px; 
    padding-bottom: 15px; 
    border-bottom: 2px solid #f0f0f0;
}
.viz-header h3 { color: #667eea; font-size: 1.2rem; flex: 1; }
.control-btn { 
    padding: 8px 16px; 
    background: #764ba2; 
    color: white; 
    border: none; 
    border-radius: 6px; 
    cursor: pointer; 
    font-size: 0.9rem; 
    transition: all 0.3s;
    font-weight: 500;
}
.control-btn:hover { background: #5d3a82; transform: scale(1.05); }
.control-btn:active { transform: scale(0.95); }

/* Controls Panel */
.controls { 
    display: none; 
    background: #f9f9f9; 
    border-radius: 10px; 
    padding: 20px; 
    margin-bottom: 20px; 
    border: 2px solid #e0e0e0;
}
.controls.show { display: block; animation: slideDown 0.3s ease-out; }

@keyframes slideDown {
    from { opacity: 0; transform: translateY(-10px); }
    to { opacity: 1; transform: translateY(0); }
}

.control-description { 
    color: #666; 
    margin-bottom: 15px; 
    font-style: italic; 
    font-size: 0.9rem;
    padding: 10px;
    background: #fff;
    border-left: 3px solid #667eea;
    border-radius: 4px;
}

.control-group { margin-bottom: 15px; }
.control-group label { 
    display: block; 
    margin-bottom: 6px; 
    color: #555; 
    font-weight: 600; 
    font-size: 0.9rem; 
}

.control-group input[type="range"] { 
    width: 100%; 
    cursor: pointer; 
    height: 6px;
    background: #ddd;
    border-radius: 3px;
    outline: none;
}

.control-group input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 18px;
    height: 18px;
    background: #667eea;
    cursor: pointer;
    border-radius: 50%;
}

.control-group select, 
.control-group input[type="date"], 
.control-group input[type="text"],
.control-group input[type="number"] { 
    width: 100%; 
    padding: 10px; 
    border: 2px solid #ddd; 
    border-radius: 6px; 
    font-size: 0.9rem; 
    transition: border-color 0.3s;
}

.control-group select:focus,
.control-group input:focus {
    border-color: #667eea;
    outline: none;
}

.control-group input[type="checkbox"] { 
    margin-right: 8px; 
    width: 18px;
    height: 18px;
    cursor: pointer;
}

.control-row { display: flex; gap: 10px; }
.control-row > * { flex: 1; }

/* Visualization Content */
.viz-content { 
    min-height: 350px; 
    position: relative; 
    background: #fafafa;
    border-radius: 8px;
    padding: 15px;
}

.placeholder { 
    padding: 80px 20px; 
    text-align: center; 
    color: #999; 
    font-size: 1.1rem; 
    background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    border-radius: 10px; 
    min-height: 300px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.placeholder p:first-child { 
    font-size: 1.3rem; 
    font-weight: bold; 
    color: #667eea; 
    margin-bottom: 10px; 
}

/* Footer */
.footer { 
    background: white; 
    border-radius: 15px; 
    padding: 25px; 
    margin-top: 30px; 
    text-align: center; 
    box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
}
.footer p { margin: 8px 0; color: #666; }
.footer a { 
    color: #667eea; 
    text-decoration: none; 
    font-weight: bold; 
    transition: color 0.3s;
}
.footer a:hover { color: #764ba2; text-decoration: underline; }

/* Responsive Design */
@media (max-width: 1024px) {
    .viz-grid { grid-template-columns: 1fr; }
    .tabs { justify-content: center; }
    .header h1 { font-size: 2rem; }
}

@media (max-width: 768px) {
    .dashboard { padding: 10px; }
    .viz-panel { padding: 15px; }
    .header { padding: 20px; }
    .header h1 { font-size: 1.5rem; }
    .tab { padding: 8px 12px; font-size: 0.85rem; }
}

/* Loading indicator */
.loading {
    display: inline-block;
    width: 20px;
    height: 20px;
    border: 3px solid #f3f3f3;
    border-top: 3px solid #667eea;
    border-radius: 50%;
    animation: spin 1s linear infinite;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
"""
        return html
        return html


    def _get_javascript(self) -> str:
        """Generate JavaScript for all 24 visualizations"""
        return """
// ============================================================================
// COMPREHENSIVE DASHBOARD WITH 24 VISUALIZATIONS
// Each visualization has its own dedicated controls
// ============================================================================

// Tab switching
function switchTab(index) {
    const tabs = document.querySelectorAll('.tab');
    const contents = document.querySelectorAll('.tab-content');
    
    tabs.forEach((tab, i) => {
        tab.classList.toggle('active', i === index);
    });
    
    contents.forEach((content, i) => {
        content.classList.toggle('active', i === index);
    });
}

// Toggle controls visibility
function toggleControls(id) {
    const controls = document.getElementById(id + '-controls');
    if (controls) {
        controls.classList.toggle('show');
    }
}

// ============================================================================
// VISUALIZATION DEFINITIONS
// ============================================================================

const visualizations = [
    // TIME-BASED VISUALIZATIONS (3)
    [
        {
            id: 'gantt', title: '1. Timeline Gantt Chart',
            description: 'Project timelines with start/end dates per user',
            controls: [
                {type: 'daterange', label: 'Date Range', ids: ['gantt-start', 'gantt-end']},
                {type: 'range', label: 'Min Hours', id: 'gantt-hours', min: 0, max: 200, value: 0},
                {type: 'select', label: 'User Selection', id: 'gantt-user', options: ['All Users']},
                {type: 'checkbox', label: 'Show Project Names', id: 'gantt-names', checked: true},
                {type: 'select', label: 'Sort By', id: 'gantt-sort', options: ['Total Hours', 'Alphabetically']}
            ]
        },
        {
            id: 'heatmap', title: '2. Time Spent Heatmap Calendar',
            description: 'Daily/weekly activity heatmap across all users',
            controls: [
                {type: 'daterange', label: 'Date Range', ids: ['heatmap-start', 'heatmap-end']},
                {type: 'range', label: 'Hour Threshold', id: 'heatmap-threshold', min: 0, max: 50, value: 5},
                {type: 'select', label: 'Aggregate By', id: 'heatmap-aggregate', options: ['Day', 'Week', 'Month']},
                {type: 'select', label: 'Color Scheme', id: 'heatmap-colors', options: ['Blues', 'Reds', 'Greens', 'Viridis']},
                {type: 'checkbox', label: 'Show Weekends', id: 'heatmap-weekends', checked: true}
            ]
        },
        {
            id: 'progress', title: '3. Progress Timeline',
            description: 'Module completion progress over time',
            controls: [
                {type: 'range', label: 'Animation Speed (ms)', id: 'progress-speed', min: 100, max: 5000, value: 1000, step: 100},
                {type: 'select', label: 'Time Granularity', id: 'progress-granularity', options: ['Daily', 'Weekly', 'Monthly']},
                {type: 'select', label: 'Stack By', id: 'progress-stack', options: ['User', 'Module']},
                {type: 'checkbox', label: 'Show Cumulative', id: 'progress-cumulative', checked: true}
            ]
        }
    ],
    
    // COMPARISON VISUALIZATIONS (3)
    [
        {
            id: 'multibar', title: '4. Multi-User Bar/Column Chart',
            description: 'Compare total hours per module across users',
            controls: [
                {type: 'range', label: 'Top N Users', id: 'multibar-top', min: 5, max: 50, value: 10, step: 5},
                {type: 'select', label: 'Group By', id: 'multibar-group', options: ['User', 'Module']},
                {type: 'checkbox', label: 'Show Average Line', id: 'multibar-average'},
                {type: 'select', label: 'Orientation', id: 'multibar-orientation', options: ['Vertical', 'Horizontal']},
                {type: 'select', label: 'Display', id: 'multibar-display', options: ['Grouped', 'Stacked']}
            ]
        },
        {
            id: 'boxplot', title: '5. Box Plot / Violin Plot',
            description: 'Distribution of hours per module across all users',
            controls: [
                {type: 'range', label: 'Outlier Threshold', id: 'boxplot-outlier', min: 0.5, max: 3, value: 1.5, step: 0.1},
                {type: 'range', label: 'Confidence Interval (%)', id: 'boxplot-ci', min: 80, max: 99, value: 95},
                {type: 'checkbox', label: 'Show Individual Points', id: 'boxplot-points'},
                {type: 'checkbox', label: 'Show Quartile Lines', id: 'boxplot-quartiles', checked: true},
                {type: 'select', label: 'Plot Type', id: 'boxplot-type', options: ['Box Plot', 'Violin Plot']},
                {type: 'checkbox', label: 'Compare Validated vs Non-Validated', id: 'boxplot-validated'}
            ]
        },
        {
            id: 'radar', title: '6. Radar/Spider Chart',
            description: 'Performance across all modules for selected users',
            controls: [
                {type: 'range', label: 'Number of Users', id: 'radar-users', min: 1, max: 6, value: 3},
                {type: 'select', label: 'Metric', id: 'radar-metric', options: ['Hours', 'Marks', 'Completion Rate']},
                {type: 'checkbox', label: 'Normalize (0-100)', id: 'radar-normalize', checked: true},
                {type: 'range', label: 'Fill Opacity', id: 'radar-opacity', min: 0, max: 1, value: 0.3, step: 0.1},
                {type: 'checkbox', label: 'Show Grid Lines', id: 'radar-grid', checked: true}
            ]
        }
    ],
    
    // PERFORMANCE VISUALIZATIONS (3)
    [
        {
            id: 'scatter', title: '7. Scatter Plot - Hours vs Score',
            description: 'Relationship between time spent and final marks',
            controls: [
                {type: 'range', label: 'X-Axis (Hours) Min', id: 'scatter-x-min', min: 0, max: 100, value: 0},
                {type: 'range', label: 'X-Axis (Hours) Max', id: 'scatter-x-max', min: 0, max: 200, value: 200},
                {type: 'range', label: 'Y-Axis (Score) Min', id: 'scatter-y-min', min: 0, max: 50, value: 0},
                {type: 'range', label: 'Y-Axis (Score) Max', id: 'scatter-y-max', min: 50, max: 100, value: 100},
                {type: 'range', label: 'Point Size', id: 'scatter-size', min: 2, max: 20, value: 5},
                {type: 'select', label: 'Color By', id: 'scatter-color', options: ['User', 'Module', 'Status']},
                {type: 'checkbox', label: 'Show Trend Line', id: 'scatter-trendline'},
                {type: 'checkbox', label: 'Validated Only', id: 'scatter-validated', checked: true}
            ]
        },
        {
            id: 'efficiency', title: '8. Efficiency Score Chart',
            description: 'Score per hour ratio analysis',
            controls: [
                {type: 'range', label: 'Efficiency Threshold', id: 'efficiency-threshold', min: 0, max: 5, value: 1, step: 0.1},
                {type: 'range', label: 'Minimum Projects', id: 'efficiency-min', min: 1, max: 10, value: 1},
                {type: 'select', label: 'Sort By', id: 'efficiency-sort', options: ['Efficiency', 'Total Hours', 'Total Projects']},
                {type: 'checkbox', label: 'Validated Only', id: 'efficiency-validated', checked: true},
                {type: 'checkbox', label: 'Highlight Top Performers', id: 'efficiency-highlight', checked: true}
            ]
        },
        {
            id: 'gauge', title: '9. Completion Rate Gauge',
            description: 'Project completion statistics',
            controls: [
                {type: 'select', label: 'Time Period', id: 'gauge-period', options: ['All Time', 'Last Month', 'Last Quarter', 'Last Year']},
                {type: 'select', label: 'View', id: 'gauge-view', options: ['Aggregate', 'By User']},
                {type: 'checkbox', label: 'Include In Progress', id: 'gauge-inprogress', checked: true},
                {type: 'checkbox', label: 'Segment by Difficulty', id: 'gauge-difficulty'}
            ]
        }
    ],
    
    // FLOW & PROGRESSION VISUALIZATIONS (3)
    [
        {
            id: 'sankey', title: '10. Sankey Diagram',
            description: 'Flow from module to module showing success/failure paths',
            controls: [
                {type: 'range', label: 'Flow Threshold', id: 'sankey-threshold', min: 1, max: 10, value: 2},
                {type: 'range', label: 'Module Depth', id: 'sankey-depth', min: 0, max: 10, value: 5},
                {type: 'checkbox', label: 'Color by Success Rate', id: 'sankey-success', checked: true},
                {type: 'checkbox', label: 'Validated Paths Only', id: 'sankey-validated'}
            ]
        },
        {
            id: 'funnel', title: '11. Funnel Chart',
            description: 'Student drop-off through modules',
            controls: [
                {type: 'select', label: 'Starting Module', id: 'funnel-start', options: ['Module 00']},
                {type: 'select', label: 'Ending Module', id: 'funnel-end', options: ['Module 10']},
                {type: 'select', label: 'Display', id: 'funnel-display', options: ['Percentage', 'Absolute Numbers']},
                {type: 'checkbox', label: 'Color by Retention', id: 'funnel-retention', checked: true}
            ]
        },
        {
            id: 'stream', title: '12. Stream Graph',
            description: 'Active students per module over time',
            controls: [
                {type: 'daterange', label: 'Date Range', ids: ['stream-start', 'stream-end']},
                {type: 'range', label: 'Smoothing Factor', id: 'stream-smooth', min: 0, max: 1, value: 0.5, step: 0.1},
                {type: 'select', label: 'Stack Order', id: 'stream-order', options: ['Appearance', 'Value']},
                {type: 'checkbox', label: 'Normalize Heights', id: 'stream-normalize'}
            ]
        }
    ],
    
    // STATISTICAL VISUALIZATIONS (3)
    [
        {
            id: 'histogram', title: '13. Histogram - Hour Distribution',
            description: 'Frequency distribution of hours spent per project',
            controls: [
                {type: 'range', label: 'Bin Size', id: 'histogram-bins', min: 5, max: 50, value: 10},
                {type: 'range', label: 'Hour Range Min', id: 'histogram-min', min: 0, max: 100, value: 0},
                {type: 'range', label: 'Hour Range Max', id: 'histogram-max', min: 0, max: 200, value: 200},
                {type: 'checkbox', label: 'Overlay Normal Distribution', id: 'histogram-normal'},
                {type: 'checkbox', label: 'Show Mean Line', id: 'histogram-mean', checked: true},
                {type: 'checkbox', label: 'Show Median Line', id: 'histogram-median', checked: true},
                {type: 'checkbox', label: 'Split by Module', id: 'histogram-split'},
                {type: 'checkbox', label: 'Log Scale', id: 'histogram-log'}
            ]
        },
        {
            id: 'cdf', title: '14. Cumulative Distribution (CDF)',
            description: 'Cumulative distribution of hours across students',
            controls: [
                {type: 'range', label: 'Highlight Percentile', id: 'cdf-percentile', min: 10, max: 99, value: 50},
                {type: 'select', label: 'View', id: 'cdf-view', options: ['Total Hours', 'Per Module']}
            ]
        },
        {
            id: 'correlation', title: '15. Correlation Matrix',
            description: 'Relationships between different metrics',
            controls: [
                {type: 'range', label: 'Correlation Strength Filter', id: 'correlation-strength', min: 0, max: 1, value: 0.3, step: 0.1},
                {type: 'select', label: 'Color Scale', id: 'correlation-colors', options: ['Diverging', 'Sequential']},
                {type: 'checkbox', label: 'Show Values on Cells', id: 'correlation-values', checked: true}
            ]
        }
    ],
    
    // LEADERBOARD VISUALIZATIONS (2)
    [
        {
            id: 'ranking', title: '16. Ranking Table with Sparklines',
            description: 'User rankings with inline mini-charts',
            controls: [
                {type: 'daterange', label: 'Date Range', ids: ['ranking-start', 'ranking-end']},
                {type: 'range', label: 'Hours Weight', id: 'ranking-hours', min: 0, max: 1, value: 0.4, step: 0.1},
                {type: 'range', label: 'Marks Weight', id: 'ranking-marks', min: 0, max: 1, value: 0.4, step: 0.1},
                {type: 'range', label: 'Speed Weight', id: 'ranking-speed', min: 0, max: 1, value: 0.2, step: 0.1},
                {type: 'select', label: 'Sort By', id: 'ranking-sort', options: ['Composite Score', 'Hours', 'Marks', 'Speed']},
                {type: 'range', label: 'Rows Per Page', id: 'ranking-rows', min: 5, max: 50, value: 10, step: 5}
            ]
        },
        {
            id: 'bump', title: '17. Bump Chart (Rank Over Time)',
            description: 'How rankings change as modules progress',
            controls: [
                {type: 'range', label: 'Time Progression', id: 'bump-time', min: 0, max: 100, value: 0},
                {type: 'range', label: 'Top N Users', id: 'bump-top', min: 3, max: 20, value: 10},
                {type: 'checkbox', label: 'Show Rank Changes', id: 'bump-changes', checked: true},
                {type: 'checkbox', label: 'Smooth Transitions', id: 'bump-smooth', checked: true}
            ]
        }
    ],
    
    // ADVANCED VISUALIZATIONS (4)
    [
        {
            id: 'treemap', title: '18. Treemap - Hours by User & Module',
            description: 'Hierarchical view of time allocation',
            controls: [
                {type: 'range', label: 'Depth Level', id: 'treemap-depth', min: 1, max: 3, value: 2},
                {type: 'range', label: 'Minimum Size (hours)', id: 'treemap-minsize', min: 0, max: 50, value: 0},
                {type: 'select', label: 'Color By', id: 'treemap-color', options: ['Efficiency', 'Status', 'Module']},
                {type: 'select', label: 'Tile Algorithm', id: 'treemap-algorithm', options: ['Squarified', 'Binary', 'Slice', 'Dice']},
                {type: 'checkbox', label: 'Show Labels', id: 'treemap-labels', checked: true}
            ]
        },
        {
            id: 'sunburst', title: '19. Sunburst Chart',
            description: 'Hierarchical breakdown with drill-down capability',
            controls: [
                {type: 'range', label: 'Inner Radius', id: 'sunburst-radius', min: 0, max: 0.8, value: 0.3, step: 0.1},
                {type: 'range', label: 'Arc Padding (px)', id: 'sunburst-padding', min: 0, max: 10, value: 2},
                {type: 'select', label: 'Color Metric', id: 'sunburst-metric', options: ['Hours', 'Efficiency', 'Completion']},
                {type: 'checkbox', label: 'Show Percentages', id: 'sunburst-percentages', checked: true}
            ]
        },
        {
            id: 'parallel', title: '20. Parallel Coordinates',
            description: 'Multi-dimensional comparison across metrics',
            controls: [
                {type: 'select', label: 'Color By', id: 'parallel-color', options: ['Cluster', 'User', 'Efficiency']},
                {type: 'checkbox', label: 'Enable Brush Filter', id: 'parallel-brush', checked: true}
            ]
        },
        {
            id: 'network', title: '21. Network Graph',
            description: 'Users connected by similar patterns/timeframes',
            controls: [
                {type: 'range', label: 'Similarity Threshold', id: 'network-threshold', min: 0, max: 1, value: 0.5, step: 0.1},
                {type: 'range', label: 'Force Strength', id: 'network-force', min: -100, max: -10, value: -30},
                {type: 'select', label: 'Node Size By', id: 'network-size', options: ['Total Hours', 'Project Count', 'Connection Count']},
                {type: 'select', label: 'Node Color By', id: 'network-color', options: ['Completion Rate', 'Efficiency', 'Cluster']},
                {type: 'checkbox', label: 'Show Connections', id: 'network-connections', checked: true},
                {type: 'select', label: 'Layout Algorithm', id: 'network-layout', options: ['Force-Directed', 'Circular', 'Radial']}
            ]
        }
    ],
    
    // INTERACTIVE COMPONENTS (3)
    [
        {
            id: 'kpi', title: '22. KPI Cards with Trends',
            description: 'Key performance indicators with trend arrows',
            controls: [
                {type: 'range', label: 'Time Comparison (days)', id: 'kpi-period', min: 7, max: 365, value: 30},
                {type: 'checkbox', label: 'Show Trend Arrows', id: 'kpi-trends', checked: true},
                {type: 'checkbox', label: 'Compare to Previous Period', id: 'kpi-compare', checked: true}
            ]
        },
        {
            id: 'datatable', title: '23. Filterable Data Table',
            description: 'Comprehensive data table with all project entries',
            controls: [
                {type: 'range', label: 'Hours Range Min', id: 'datatable-hours-min', min: 0, max: 100, value: 0},
                {type: 'range', label: 'Hours Range Max', id: 'datatable-hours-max', min: 0, max: 200, value: 200},
                {type: 'range', label: 'Score Range Min', id: 'datatable-score-min', min: 0, max: 50, value: 0},
                {type: 'range', label: 'Score Range Max', id: 'datatable-score-max', min: 50, max: 100, value: 100},
                {type: 'daterange', label: 'Date Range', ids: ['datatable-start', 'datatable-end']}
            ]
        },
        {
            id: 'race', title: '24. Animated Race Bar Chart',
            description: 'Top students progressing through modules with animation',
            controls: [
                {type: 'range', label: 'Animation Speed (ms)', id: 'race-speed', min: 100, max: 2000, value: 500, step: 100},
                {type: 'select', label: 'Time Step', id: 'race-step', options: ['Daily', 'Weekly', 'Monthly']},
                {type: 'range', label: 'Number of Bars', id: 'race-bars', min: 5, max: 20, value: 10},
                {type: 'select', label: 'Metric', id: 'race-metric', options: ['Cumulative Hours', 'Modules Completed', 'Total Score']}
            ]
        }
    ]
];

// ============================================================================
// GENERATE DASHBOARD HTML
// ============================================================================

function generateDashboard() {
    const content = document.getElementById('content');
    const tabTitles = [
        '⏰ Time-Based Visualizations',
        '📈 Comparison Visualizations',
        '🎯 Performance Visualizations',
        '🔄 Flow & Progression Visualizations',
        '📊 Statistical Visualizations',
        '🏆 Leaderboard Visualizations',
        '🎨 Advanced Visualizations',
        '🎯 Interactive Dashboard Components'
    ];
    
    let html = '';
    
    visualizations.forEach((group, groupIndex) => {
        html += `<div class="tab-content ${groupIndex === 0 ? 'active' : ''}">`;
        html += `<h2 class="category-title">${tabTitles[groupIndex]}</h2>`;
        html += `<div class="viz-grid">`;
        
        group.forEach(viz => {
            html += `
                <div class="viz-panel">
                    <div class="viz-header">
                        <h3>${viz.title}</h3>
                        <button class="control-btn" onclick="toggleControls('${viz.id}')">⚙️ Controls</button>
                    </div>
                    <div id="${viz.id}-controls" class="controls">
                        <p class="control-description">${viz.description}</p>
            `;
            
            // Generate controls
            viz.controls.forEach(control => {
                html += `<div class="control-group">`;
                
                if (control.type === 'range') {
                    html += `
                        <label>${control.label}: <span id="${control.id}-val">${control.value}</span></label>
                        <input type="range" id="${control.id}" 
                               min="${control.min}" max="${control.max}" value="${control.value}" 
                               ${control.step ? `step="${control.step}"` : ''}
                               oninput="document.getElementById('${control.id}-val').textContent=this.value">
                    `;
                } else if (control.type === 'select') {
                    html += `
                        <label>${control.label}</label>
                        <select id="${control.id}">
                            ${control.options.map(opt => `<option value="${opt.toLowerCase().replace(/\s+/g, '-')}">${opt}</option>`).join('')}
                        </select>
                    `;
                } else if (control.type === 'checkbox') {
                    html += `
                        <label>
                            <input type="checkbox" id="${control.id}" ${control.checked ? 'checked' : ''}>
                            ${control.label}
                        </label>
                    `;
                } else if (control.type === 'daterange') {
                    html += `
                        <label>${control.label}</label>
                        <div class="control-row">
                            <input type="date" id="${control.ids[0]}">
                            <input type="date" id="${control.ids[1]}">
                        </div>
                    `;
                }
                
                html += `</div>`;
            });
            
            html += `
                    </div>
                    <div id="${viz.id}-chart" class="viz-content">
                        <div class="placeholder">
                            <p>📊 ${viz.title}</p>
                            <p style="font-size: 0.9rem; margin-top: 10px; color: #666;">${viz.description}</p>
                            <p style="font-size: 0.85rem; margin-top: 15px; color: #999;">
                                ${rawData.length > 0 ? 'Ready to visualize ' + rawData.length + ' users' : 'Waiting for data...'}
                            </p>
                        </div>
                    </div>
                </div>
            `;
        });
        
        html += `</div></div>`;
    });
    
    content.innerHTML = html;
    
    // Log initialization
    console.log('✓ Dashboard initialized with 24 visualizations');
    console.log('✓ Data: ' + rawData.length + ' users, ' + Object.keys(rawStats.modules || {}).length + ' modules');
    console.log('✓ Each visualization has individual controls');
}





// ============================================================================
// SIMPLE CHART RENDERING (NO EXTERNAL DEPENDENCIES)
// ============================================================================

// Render Top Users Bar Chart with CSS
function renderTopUsersChart() {
    const container = document.getElementById('multibar-chart');
    const topN = parseInt(document.getElementById('multibar-top')?.value || 10);
    const sortedUsers = rawData
        .sort((a, b) => b.total_python_hours - a.total_python_hours)
        .slice(0, topN);
    
    const maxHours = Math.max(...sortedUsers.map(u => u.total_python_hours));
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 20px; color: #667eea;">Top Users by Total Hours</h4>';
    
    sortedUsers.forEach(user => {
        const percentage = (user.total_python_hours / maxHours) * 100;
        html += `
            <div style="margin-bottom: 15px;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                    <span style="font-weight: 600;">${user.login}</span>
                    <span style="color: #666;">${user.total_python_hours.toFixed(1)}h</span>
                </div>
                <div style="background: #e0e0e0; height: 30px; border-radius: 5px; overflow: hidden;">
                    <div style="background: linear-gradient(90deg, #667eea, #764ba2); height: 100%; width: ${percentage}%; transition: width 0.5s;"></div>
                </div>
            </div>
        `;
    });
    
    html += '</div>';
    container.innerHTML = html;
}

// Render Module Average Times Chart with CSS
function renderModuleAvgChart() {
    const container = document.getElementById('radar-chart');
    
    const moduleStats = {};
    rawData.forEach(user => {
        user.python_projects.forEach(proj => {
            const name = proj.project_name;
            if (!moduleStats[name]) {
                moduleStats[name] = { total: 0, count: 0 };
            }
            moduleStats[name].total += proj.time_spent_hours;
            moduleStats[name].count += 1;
        });
    });
    
    const modules = Object.keys(moduleStats)
        .map(name => ({ name, avg: moduleStats[name].total / moduleStats[name].count }))
        .sort((a, b) => b.avg - a.avg)
        .slice(0, 10);
    
    const maxAvg = Math.max(...modules.map(m => m.avg));
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 20px; color: #764ba2;">Average Time per Module</h4>';
    
    modules.forEach(module => {
        const percentage = (module.avg / maxAvg) * 100;
        html += `
            <div style="margin-bottom: 15px;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                    <span style="font-weight: 600; font-size: 0.9rem;">${module.name}</span>
                    <span style="color: #666;">${module.avg.toFixed(1)}h</span>
                </div>
                <div style="background: #e0e0e0; height: 25px; border-radius: 5px; overflow: hidden;">
                    <div style="background: linear-gradient(90deg, #764ba2, #667eea); height: 100%; width: ${percentage}%;"></div>
                </div>
            </div>
        `;
    });
    
    html += '</div>';
    container.innerHTML = html;
}

// Render Scatter Plot with SVG
function renderScatterChart() {
    const container = document.getElementById('scatter-chart');
    const width = 500;
    const height = 350;
    const padding = 50;
    
    const scatterData = [];
    rawData.forEach(user => {
        user.python_projects.forEach(proj => {
            if (proj.final_mark !== null && proj.final_mark !== undefined && proj.time_spent_hours > 0) {
                scatterData.push({
                    x: proj.time_spent_hours,
                    y: proj.final_mark,
                    user: user.login,
                    project: proj.project_name
                });
            }
        });
    });
    
    if (scatterData.length === 0) {
        container.innerHTML = '<div style="padding: 40px; text-align: center; color: #999;">No data available</div>';
        return;
    }
    
    const maxX = Math.max(...scatterData.map(d => d.x));
    const maxY = 100;
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 15px; color: #667eea;">Hours vs Final Score</h4>';
    html += `<svg width="${width}" height="${height}" style="border: 1px solid #e0e0e0; border-radius: 8px; background: white;">`;
    
    // Grid lines
    for (let i = 0; i <= 5; i++) {
        const y = padding + (height - 2 * padding) * i / 5;
        html += `<line x1="${padding}" y1="${y}" x2="${width - padding}" y2="${y}" stroke="#e0e0e0" stroke-width="1"/>`;
        html += `<text x="${padding - 10}" y="${y + 5}" text-anchor="end" font-size="12" fill="#666">${100 - i * 20}</text>`;
    }
    
    // Axes
    html += `<line x1="${padding}" y1="${padding}" x2="${padding}" y2="${height - padding}" stroke="#333" stroke-width="2"/>`;
    html += `<line x1="${padding}" y1="${height - padding}" x2="${width - padding}" y2="${height - padding}" stroke="#333" stroke-width="2"/>`;
    
    // Data points
    scatterData.forEach(point => {
        const x = padding + (point.x / maxX) * (width - 2 * padding);
        const y = height - padding - (point.y / maxY) * (height - 2 * padding);
        html += `<circle cx="${x}" cy="${y}" r="5" fill="#667eea" opacity="0.7" stroke="#764ba2" stroke-width="2">
            <title>${point.user} - ${point.project}\nHours: ${point.x.toFixed(1)}\nScore: ${point.y}</title>
        </circle>`;
    });
    
    // Labels
    html += `<text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-size="14" fill="#333">Hours Spent</text>`;
    html += `<text x="20" y="${height / 2}" text-anchor="middle" font-size="14" fill="#333" transform="rotate(-90 20 ${height / 2})">Final Score</text>`;
    
    html += '</svg></div>';
    container.innerHTML = html;
}

// Render Status Distribution with CSS Pie Chart
function renderStatusChart() {
    const container = document.getElementById('boxplot-chart');
    
    const statusCount = { finished: 0, in_progress: 0, waiting: 0 };
    rawData.forEach(user => {
        user.python_projects.forEach(proj => {
            if (proj.status && statusCount.hasOwnProperty(proj.status)) {
                statusCount[proj.status]++;
            }
        });
    });
    
    const total = statusCount.finished + statusCount.in_progress + statusCount.waiting;
    const finishedPct = (statusCount.finished / total * 100).toFixed(1);
    const inProgressPct = (statusCount.in_progress / total * 100).toFixed(1);
    const waitingPct = (statusCount.waiting / total * 100).toFixed(1);
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 20px; color: #667eea;">Project Status Distribution</h4>';
    html += '<div style="display: flex; gap: 30px; align-items: center;">';
    
    // Simple pie chart representation with circles
    html += '<div style="flex: 1;">';
    html += `<div style="margin-bottom: 15px;">
        <div style="display: inline-block; width: 20px; height: 20px; background: #4BC0C0; border-radius: 3px; margin-right: 10px;"></div>
        <span style="font-weight: 600;">Finished:</span> ${statusCount.finished} (${finishedPct}%)
    </div>`;
    html += `<div style="margin-bottom: 15px;">
        <div style="display: inline-block; width: 20px; height: 20px; background: #FFCE56; border-radius: 3px; margin-right: 10px;"></div>
        <span style="font-weight: 600;">In Progress:</span> ${statusCount.in_progress} (${inProgressPct}%)
    </div>`;
    html += `<div style="margin-bottom: 15px;">
        <div style="display: inline-block; width: 20px; height: 20px; background: #FF6384; border-radius: 3px; margin-right: 10px;"></div>
        <span style="font-weight: 600;">Waiting:</span> ${statusCount.waiting} (${waitingPct}%)
    </div>`;
    html += '</div>';
    
    // Visual bars
    html += '<div style="flex: 1;">';
    html += `<div style="background: #4BC0C0; height: 40px; width: ${finishedPct}%; margin-bottom: 5px; border-radius: 5px;"></div>`;
    html += `<div style="background: #FFCE56; height: 40px; width: ${inProgressPct}%; margin-bottom: 5px; border-radius: 5px;"></div>`;
    html += `<div style="background: #FF6384; height: 40px; width: ${waitingPct}%; border-radius: 5px;"></div>`;
    html += '</div>';
    
    html += '</div></div>';
    container.innerHTML = html;
}

// Render Time Distribution Histogram with CSS
function renderHistogramChart() {
    const container = document.getElementById('histogram-chart');
    
    const hours = rawData.map(u => u.total_python_hours);
    const bins = 10;
    const max = Math.max(...hours);
    const binSize = max / bins;
    
    const histogram = Array(bins).fill(0);
    hours.forEach(h => {
        const binIndex = Math.min(Math.floor(h / binSize), bins - 1);
        histogram[binIndex]++;
    });
    
    const maxCount = Math.max(...histogram);
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 20px; color: #4BC0C0;">Hours Distribution</h4>';
    html += '<div style="display: flex; align-items: flex-end; gap: 5px; height: 200px;">';
    
    histogram.forEach((count, i) => {
        const height = (count / maxCount) * 180;
        const label = `${(i * binSize).toFixed(0)}-${((i + 1) * binSize).toFixed(0)}h`;
        html += `
            <div style="flex: 1; display: flex; flex-direction: column; align-items: center;">
                <div style="color: #666; font-size: 0.8rem; margin-bottom: 5px;">${count}</div>
                <div style="background: linear-gradient(180deg, #4BC0C0, #45B0B0); width: 100%; height: ${height}px; border-radius: 5px 5px 0 0; transition: height 0.5s;" title="${count} users"></div>
                <div style="font-size: 0.7rem; color: #666; margin-top: 5px; transform: rotate(-45deg); transform-origin: top left;">${label}</div>
            </div>
        `;
    });
    
    html += '</div></div>';
    container.innerHTML = html;
}

// Render Efficiency Chart with CSS
function renderEfficiencyChart() {
    const container = document.getElementById('efficiency-chart');
    
    const userEfficiency = rawData.map(user => {
        let totalScore = 0;
        let totalHours = 0;
        let validProjects = 0;
        
        user.python_projects.forEach(proj => {
            if (proj.final_mark !== null && proj.final_mark !== undefined && proj.time_spent_hours > 0) {
                totalScore += proj.final_mark;
                totalHours += proj.time_spent_hours;
                validProjects++;
            }
        });
        
        return {
            login: user.login,
            efficiency: totalHours > 0 ? totalScore / totalHours : 0,
            totalHours: totalHours
        };
    }).filter(u => u.efficiency > 0)
      .sort((a, b) => b.efficiency - a.efficiency)
      .slice(0, 15);
    
    const maxEff = Math.max(...userEfficiency.map(u => u.efficiency));
    
    let html = '<div style="padding: 20px;">';
    html += '<h4 style="margin-bottom: 20px; color: #FF9F40;">Efficiency Score (Score per Hour)</h4>';
    
    userEfficiency.forEach(user => {
        const percentage = (user.efficiency / maxEff) * 100;
        html += `
            <div style="margin-bottom: 15px;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                    <span style="font-weight: 600;">${user.login}</span>
                    <span style="color: #666;">${user.efficiency.toFixed(2)} pts/hr (${user.totalHours.toFixed(1)}h)</span>
                </div>
                <div style="background: #e0e0e0; height: 25px; border-radius: 5px; overflow: hidden;">
                    <div style="background: linear-gradient(90deg, #FF9F40, #FFCE56); height: 100%; width: ${percentage}%;"></div>
                </div>
            </div>
        `;
    });
    
    html += '</div>';
    container.innerHTML = html;
}

// Initialize all working charts
function initializeWorkingCharts() {
    console.log('Initializing CSS-based charts (no external dependencies)...');
    
    if (rawData && rawData.length > 0) {
        try {
            // Comparison tab - chart 4
            if (document.getElementById('multibar-chart')) renderTopUsersChart();
            // Comparison tab - chart 6
            if (document.getElementById('radar-chart')) renderModuleAvgChart();
            // Performance tab - chart 7
            if (document.getElementById('scatter-chart')) renderScatterChart();
            // Comparison tab - chart 5
            if (document.getElementById('boxplot-chart')) renderStatusChart();
            // Statistical tab - chart 13
            if (document.getElementById('histogram-chart')) renderHistogramChart();
            // Performance tab - chart 8
            if (document.getElementById('efficiency-chart')) renderEfficiencyChart();
            
            console.log('✓ All charts initialized successfully');
        } catch (error) {
            console.error('Error initializing charts:', error);
        }
    }
}

// Initialize dashboard when page loads
document.addEventListener('DOMContentLoaded', function() {
    generateDashboard();
    // Give the DOM time to render, then initialize charts
    setTimeout(initializeWorkingCharts, 100);
});
generateDashboard();
setTimeout(initializeWorkingCharts, 100);
"""
