"""
Demo script showing example output of the Python Time Tracker
This simulates what the actual output would look like
"""

import json
from datetime import datetime, timedelta


def create_demo_output():
    """Create demonstration output data"""
    
    # Create sample data that would be generated by the real application
    demo_data = [
        {
            "user_id": 12345,
            "login": "student-a",
            "email": "student-a@student.42.fr",
            "cursus_level": 5.42,
            "python_projects": [
                {
                    "project_name": "Python - 0 - Starting",
                    "project_slug": "piscine-python-django-0-starting",
                    "start_date": "2024-01-15T10:00:00+00:00",
                    "end_date": "2024-01-22T18:30:00+00:00",
                    "time_spent_hours": 45.5,
                    "status": "finished",
                    "final_mark": 100,
                    "validated": True
                },
                {
                    "project_name": "Python - 1 - Base Django",
                    "project_slug": "piscine-python-django-1-base-django",
                    "start_date": "2024-01-23T09:00:00+00:00",
                    "end_date": "2024-02-05T16:45:00+00:00",
                    "time_spent_hours": 67.25,
                    "status": "finished",
                    "final_mark": 95,
                    "validated": True
                },
                {
                    "project_name": "Python - 2 - SQL",
                    "project_slug": "piscine-python-django-2-sql",
                    "start_date": "2024-02-06T10:30:00+00:00",
                    "end_date": "2024-02-20T14:20:00+00:00",
                    "time_spent_hours": 52.75,
                    "status": "finished",
                    "final_mark": 88,
                    "validated": True
                }
            ],
            "total_python_hours": 165.5
        },
        {
            "user_id": 12346,
            "login": "student-b",
            "email": "student-b@student.42.fr",
            "cursus_level": 4.89,
            "python_projects": [
                {
                    "project_name": "Python - 0 - Starting",
                    "project_slug": "piscine-python-django-0-starting",
                    "start_date": "2024-01-10T11:00:00+00:00",
                    "end_date": "2024-01-20T17:30:00+00:00",
                    "time_spent_hours": 38.25,
                    "status": "finished",
                    "final_mark": 125,
                    "validated": True
                },
                {
                    "project_name": "Python - 1 - Base Django",
                    "project_slug": "piscine-python-django-1-base-django",
                    "start_date": "2024-01-21T08:00:00+00:00",
                    "end_date": "2024-02-10T19:15:00+00:00",
                    "time_spent_hours": 82.5,
                    "status": "finished",
                    "final_mark": 110,
                    "validated": True
                }
            ],
            "total_python_hours": 120.75
        },
        {
            "user_id": 12347,
            "login": "student-c",
            "email": "student-c@student.42.fr",
            "cursus_level": 6.12,
            "python_projects": [
                {
                    "project_name": "ft_transcendence",
                    "project_slug": "ft_transcendence",
                    "start_date": "2024-03-01T09:00:00+00:00",
                    "end_date": "2024-04-15T18:00:00+00:00",
                    "time_spent_hours": 234.5,
                    "status": "finished",
                    "final_mark": 100,
                    "validated": True
                }
            ],
            "total_python_hours": 234.5
        }
    ]
    
    return demo_data


def display_demo():
    """Display demo output"""
    print("=" * 80)
    print("DEMONSTRATION: 42 API Python Time Tracker Output")
    print("=" * 80)
    print("\nThis shows what the actual application output would look like")
    print("when run with real 42 API credentials.\n")
    
    data = create_demo_output()
    
    # Save to file
    filename = "demo_output.json"
    with open(filename, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"✓ Sample data saved to: {filename}\n")
    
    # Display summary
    print("SUMMARY:")
    print("-" * 80)
    print(f"Total students analyzed: {len(data)}")
    print(f"Total Python projects: {sum(len(s['python_projects']) for s in data)}")
    print(f"Total hours tracked: {sum(s['total_python_hours'] for s in data):.2f} hours\n")
    
    # Display per-student details
    print("STUDENT DETAILS:")
    print("-" * 80)
    
    for student in data:
        print(f"\n👤 {student['login']} (Level {student['cursus_level']})")
        print(f"   Total Python hours: {student['total_python_hours']} hours")
        print(f"   Projects completed: {len(student['python_projects'])}")
        
        for i, project in enumerate(student['python_projects'], 1):
            status_icon = "✓" if project['validated'] else "✗"
            print(f"\n   {i}. {project['project_name']}")
            print(f"      Status: {status_icon} {project['status'].upper()}")
            print(f"      Time spent: {project['time_spent_hours']} hours")
            print(f"      Final mark: {project['final_mark']}/100")
            print(f"      Period: {project['start_date'][:10]} to {project['end_date'][:10]}")
    
    print("\n" + "=" * 80)
    print("To run with real data:")
    print("  1. Configure your .env file with 42 API credentials")
    print("  2. Run: python main.py")
    print("=" * 80)


if __name__ == "__main__":
    display_demo()
